"""Initial schema

Revision ID: 000000000000
Revises: 
Create Date: 2026-09-09 20:20:51.552364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000000000000'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    # ### commands auto generated by Alembic - please adjust! ###
    if not inspector.has_table('contractors'):
        op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('contractors'):
        op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    if not inspector.has_table('contractors'):
        op.create_index(op.f('ix_contractors_name'), 'contractors', ['name'], unique=False)
    if not inspector.has_table('data_sources'):
        op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('data_sources'):
        op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    if not inspector.has_table('users'):
        op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('users'):
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    if not inspector.has_table('users'):
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    if not inspector.has_table('audit_logs'):
        op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('audit_logs'):
        op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    if not inspector.has_table('mps'):
        op.create_table('mps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tenure', sa.String(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('constituency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('mps'):
        op.create_index(op.f('ix_mps_id'), 'mps', ['id'], unique=False)
    if not inspector.has_table('pre_sanction_assessments'):
        op.create_table('pre_sanction_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=True),
    sa.Column('proposed_category', sa.String(), nullable=True),
    sa.Column('proposed_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('pre_sanction_assessments'):
        op.create_index(op.f('ix_pre_sanction_assessments_id'), 'pre_sanction_assessments', ['id'], unique=False)
    if not inspector.has_table('projects'):
        op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=True),
    sa.Column('work_stage', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('constituency', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_category', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sanctioned_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gps_provenance', sa.String(), server_default='UNAVAILABLE', nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_completion', sa.Date(), nullable=True),
    sa.Column('actual_completion', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('projects'):
        op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    if not inspector.has_table('projects'):
        op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    if not inspector.has_table('projects'):
        op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    if not inspector.has_table('projects'):
        op.create_index(op.f('ix_projects_work_id'), 'projects', ['work_id'], unique=False)
    if not inspector.has_table('compliance_assessments'):
        op.create_table('compliance_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('coverage_percentage', sa.Float(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('not_assessable_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('compliance_assessments'):
        op.create_index(op.f('ix_compliance_assessments_id'), 'compliance_assessments', ['id'], unique=False)
    if not inspector.has_table('early_warnings'):
        op.create_table('early_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('warning_type', sa.String(), nullable=False),
    sa.Column('warning_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('trigger_signature', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), server_default='AI ASSESSMENT', nullable=False),
    sa.Column('assessment_coverage', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('early_warnings'):
        op.create_index(op.f('ix_early_warnings_id'), 'early_warnings', ['id'], unique=False)
    if not inspector.has_table('early_warnings'):
        op.create_index(op.f('ix_early_warnings_status'), 'early_warnings', ['status'], unique=False)
    if not inspector.has_table('early_warnings'):
        op.create_index(op.f('ix_early_warnings_trigger_signature'), 'early_warnings', ['trigger_signature'], unique=True)
    if not inspector.has_table('early_warnings'):
        op.create_index(op.f('ix_early_warnings_warning_type'), 'early_warnings', ['warning_type'], unique=False)
    if not inspector.has_table('predictive_completion_assessments'):
        op.create_table('predictive_completion_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('drivers', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('missing_data', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), server_default='AI ASSESSMENT', nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('predictive_completion_assessments'):
        op.create_index(op.f('ix_predictive_completion_assessments_id'), 'predictive_completion_assessments', ['id'], unique=False)
    if not inspector.has_table('project_contractors'):
        op.create_table('project_contractors',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'contractor_id')
    )
    if not inspector.has_table('project_financials'):
        op.create_table('project_financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('expenditure', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('project_financials'):
        op.create_index(op.f('ix_project_financials_id'), 'project_financials', ['id'], unique=False)
    if not inspector.has_table('project_progress'):
        op.create_table('project_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('project_progress'):
        op.create_index(op.f('ix_project_progress_id'), 'project_progress', ['id'], unique=False)
    if not inspector.has_table('review_logs'):
        op.create_table('review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('review_logs'):
        op.create_index(op.f('ix_review_logs_id'), 'review_logs', ['id'], unique=False)
    if not inspector.has_table('reviews'):
        op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('reviews'):
        op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    if not inspector.has_table('risk_assessments'):
        op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('overall_risk_level', sa.String(), nullable=False),
    sa.Column('assessment_status', sa.String(), nullable=True),
    sa.Column('assessment_coverage_pct', sa.Float(), nullable=True),
    sa.Column('assessable_indicator_count', sa.Integer(), nullable=True),
    sa.Column('total_indicator_count', sa.Integer(), nullable=True),
    sa.Column('risk_reasons', sa.JSON(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('risk_assessments'):
        op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    if not inspector.has_table('risk_history'):
        op.create_table('risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('indicator_snapshot', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('risk_history'):
        op.create_index(op.f('ix_risk_history_id'), 'risk_history', ['id'], unique=False)
    if not inspector.has_table('compliance_checks'):
        op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(), nullable=False),
    sa.Column('check_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), server_default='UNAVAILABLE', nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('available_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('compliance_checks'):
        op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    if not inspector.has_table('risk_indicators'):
        op.create_table('risk_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('data_provenance', sa.String(), server_default='UNAVAILABLE', nullable=False),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('risk_indicators'):
        op.create_index(op.f('ix_risk_indicators_id'), 'risk_indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_indicators_id'), table_name='risk_indicators')
    op.drop_table('risk_indicators')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_risk_history_id'), table_name='risk_history')
    op.drop_table('risk_history')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_review_logs_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_project_progress_id'), table_name='project_progress')
    op.drop_table('project_progress')
    op.drop_index(op.f('ix_project_financials_id'), table_name='project_financials')
    op.drop_table('project_financials')
    op.drop_table('project_contractors')
    op.drop_index(op.f('ix_predictive_completion_assessments_id'), table_name='predictive_completion_assessments')
    op.drop_table('predictive_completion_assessments')
    op.drop_index(op.f('ix_early_warnings_warning_type'), table_name='early_warnings')
    op.drop_index(op.f('ix_early_warnings_trigger_signature'), table_name='early_warnings')
    op.drop_index(op.f('ix_early_warnings_status'), table_name='early_warnings')
    op.drop_index(op.f('ix_early_warnings_id'), table_name='early_warnings')
    op.drop_table('early_warnings')
    op.drop_index(op.f('ix_compliance_assessments_id'), table_name='compliance_assessments')
    op.drop_table('compliance_assessments')
    op.drop_index(op.f('ix_projects_work_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pre_sanction_assessments_id'), table_name='pre_sanction_assessments')
    op.drop_table('pre_sanction_assessments')
    op.drop_index(op.f('ix_mps_id'), table_name='mps')
    op.drop_table('mps')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_contractors_name'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
