"""Add predictive completion assessment

Revision ID: b9bea6aa35e9
Revises: 144df3b5a80e
Create Date: 2026-09-09 19:53:47.925707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bea6aa35e9'
down_revision: Union[str, Sequence[str], None] = '144df3b5a80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    # ### commands auto generated by Alembic - please adjust! ###
    if not inspector.has_table('predictive_completion_assessments'):
        op.create_table('predictive_completion_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('drivers', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('missing_data', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), server_default='AI ASSESSMENT', nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not inspector.has_table('predictive_completion_assessments'):
        op.create_index(op.f('ix_predictive_completion_assessments_id'), 'predictive_completion_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictive_completion_assessments_id'), table_name='predictive_completion_assessments')
    op.drop_table('predictive_completion_assessments')
    # ### end Alembic commands ###
