"""add early warnings

Revision ID: 16cf8924411d
Revises: 22ee332d0f76
Create Date: 2026-09-09 14:59:35.237778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cf8924411d'
down_revision: Union[str, Sequence[str], None] = '22ee332d0f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('early_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('warning_type', sa.String(), nullable=False),
    sa.Column('warning_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('trigger_signature', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), server_default='AI ASSESSMENT', nullable=False),
    sa.Column('assessment_coverage', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_early_warnings_id'), 'early_warnings', ['id'], unique=False)
    op.create_index(op.f('ix_early_warnings_status'), 'early_warnings', ['status'], unique=False)
    op.create_index(op.f('ix_early_warnings_trigger_signature'), 'early_warnings', ['trigger_signature'], unique=True)
    op.create_index(op.f('ix_early_warnings_warning_type'), 'early_warnings', ['warning_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_early_warnings_warning_type'), table_name='early_warnings')
    op.drop_index(op.f('ix_early_warnings_trigger_signature'), table_name='early_warnings')
    op.drop_index(op.f('ix_early_warnings_status'), table_name='early_warnings')
    op.drop_index(op.f('ix_early_warnings_id'), table_name='early_warnings')
    op.drop_table('early_warnings')
    # ### end Alembic commands ###
