"""phase_6a_gps_provenance

Revision ID: 22ee332d0f76
Revises: 42a54cbdf4f0
Create Date: 2026-09-09 14:07:48.769495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ee332d0f76'
down_revision: Union[str, Sequence[str], None] = '42a54cbdf4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gps_provenance', sa.String(), server_default='UNAVAILABLE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'gps_provenance')
    # ### end Alembic commands ###
