"""Phase 3 indicators

Revision ID: 28116f80fcf9
Revises: 2f5736f52bda
Create Date: 2026-09-07 21:42:44.249261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28116f80fcf9'
down_revision: Union[str, Sequence[str], None] = '2f5736f52bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.alter_column('score', existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table('risk_history', schema=None) as batch_op:
        batch_op.alter_column('risk_score', existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table('risk_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indicator', sa.String(), server_default='legacy', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='ASSESSABLE', nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data_provenance', sa.String(), server_default='UNAVAILABLE', nullable=False))
        batch_op.drop_column('reference_value')
        batch_op.drop_column('indicator_type')
        batch_op.drop_column('observed_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observed_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('indicator_type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('reference_value', sa.FLOAT(), nullable=True))
        batch_op.drop_column('data_provenance')
        batch_op.drop_column('evidence')
        batch_op.drop_column('confidence')
        batch_op.drop_column('score')
        batch_op.drop_column('status')
        batch_op.drop_column('indicator')

    with op.batch_alter_table('risk_history', schema=None) as batch_op:
        batch_op.alter_column('risk_score', existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.alter_column('score', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
