"""phase_5_risk_history

Revision ID: 5f563d161682
Revises: 2a97e36102ee
Create Date: 2026-09-08 14:15:17.055674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f563d161682'
down_revision: Union[str, Sequence[str], None] = '2a97e36102ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('assessment_status', sa.String(), nullable=True))
    op.add_column('risk_assessments', sa.Column('assessment_coverage_pct', sa.Float(), nullable=True))
    op.add_column('risk_assessments', sa.Column('assessable_indicator_count', sa.Integer(), nullable=True))
    op.add_column('risk_assessments', sa.Column('total_indicator_count', sa.Integer(), nullable=True))
    op.add_column('risk_assessments', sa.Column('risk_reasons', sa.JSON(), nullable=True))
    op.add_column('risk_assessments', sa.Column('engine_version', sa.String(), server_default='5.0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_assessments', 'engine_version')
    op.drop_column('risk_assessments', 'risk_reasons')
    op.drop_column('risk_assessments', 'total_indicator_count')
    op.drop_column('risk_assessments', 'assessable_indicator_count')
    op.drop_column('risk_assessments', 'assessment_coverage_pct')
    op.drop_column('risk_assessments', 'assessment_status')
    # ### end Alembic commands ###
